# Base Docker Compose configuration
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_CHAT_COMPLETION_DEPLOYED_MODEL_NAME=${AZURE_OPENAI_CHAT_COMPLETION_DEPLOYED_MODEL_NAME}
      - AZURE_OPENAI_EMBEDDING_DEPLOYED_MODEL_NAME=${AZURE_OPENAI_EMBEDDING_DEPLOYED_MODEL_NAME}
      - AZURE_SEARCH_SERVICE_ENDPOINT=${AZURE_SEARCH_SERVICE_ENDPOINT}
      - AZURE_SEARCH_ADMIN_KEY=${AZURE_SEARCH_ADMIN_KEY}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}  # Changed from SAS_TOKEN
      - BLOB_CONTAINER_NAME=${BLOB_CONTAINER_NAME}
      - SAS_TOKEN_EXPIRY_MINUTES=${SAS_TOKEN_EXPIRY_MINUTES:-30}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge